/**
 * NarutoCardGuide's sole executable boundary to tcg-engines.
 *
 * This file deliberately does not contain Naruto rules. It only adapts the
 * upstream state machine for the UI and the authoritative PvP Worker. When
 * tcg-engines adds an action or changes its public API, this is the one place
 * to review before changing either simulator mode.
 */
import {
  applyAction,
  chooseAiAction,
  createInitialState,
  deciderOf,
  PREVIEW_DECKS,
  previewDeckList,
} from '../../../vendor/tcg-engines/submodules/naruto/packages/engine/src/index.ts';
import type {
  Action,
  CardInstance,
  CharacterInstance,
  GameState,
  PlayerId,
  RulesProfile,
  SupportInstance,
} from '../../../vendor/tcg-engines/submodules/naruto/packages/engine/src/index.ts';
import { getCardById } from '@tcg-engines/naruto-cards';
import type { CardDefinition } from '@tcg-engines/naruto-cards';

export type { Action, CardInstance, CharacterInstance, GameState, PlayerId, RulesProfile, SupportInstance };

export type NarutoActionOption = Readonly<{ label: string; action: Action }>;
export type NarutoPreviewMatchOptions = Readonly<{
  seed?: number;
  firstPlayer?: PlayerId;
  names?: Partial<Record<PlayerId, string>>;
}>;

/** Create the same upstream Preview matchup for both AI and PvP. */
export function createNarutoPreviewMatch(options: NarutoPreviewMatchOptions = {}): GameState {
  return createInitialState({
    seed: options.seed ?? 42,
    decks: {
      p1: previewDeckList(PREVIEW_DECKS[0]!),
      p2: previewDeckList(PREVIEW_DECKS[2]!),
    },
    firstPlayer: options.firstPlayer,
    names: options.names,
  });
}

/** The only action-validation gateway owned by NarutoCardGuide. */
export function applyNarutoAction(state: GameState, action: Action): GameState {
  return applyAction(state, action);
}

export function narutoActionIsLegal(state: GameState, action: Action): boolean {
  return applyNarutoAction(state, action) !== state;
}

/** Keep computer turns generated by the upstream policy, then validate them upstream. */
export function chooseNarutoAiAction(state: GameState, player: PlayerId): Action | null {
  return chooseAiAction(state, player);
}

export function narutoDecider(state: GameState): PlayerId | null {
  return deciderOf(state);
}

export function narutoCard(cardId: string): CardDefinition | undefined {
  return getCardById(cardId);
}

export function narutoCardName(cardId: string): string {
  return narutoCard(cardId)?.nameEn ?? cardId;
}

/**
 * UI/transport action catalog. It enumerates possible action payloads but
 * delegates every legality decision to `applyNarutoAction` above. This is not
 * a second rules engine.
 */
export function availableNarutoActions(state: GameState, player: PlayerId): NarutoActionOption[] {
  if (narutoDecider(state) !== player || state.winner) return [];
  const legal = (label: string, action: Action): NarutoActionOption[] =>
    narutoActionIsLegal(state, action) ? [{ label, action }] : [];
  const actor = state.players[player];
  const opponentId: PlayerId = player === 'p1' ? 'p2' : 'p1';
  const opponent = state.players[opponentId];

  if (state.awaitingMulligan === player) {
    return [
      ...legal('Keep hand', { type: 'MULLIGAN', player, keep: true }),
      ...legal('Mulligan', { type: 'MULLIGAN', player, keep: false }),
    ];
  }
  if (state.pendingChoice?.player === player) {
    const choices = state.pendingChoice.options.flatMap((option) =>
      legal(`Choose ${narutoCardName(option.cardId)}`, {
        type: 'RESOLVE_CHOICE',
        player,
        key: option.key,
      }),
    );
    return state.pendingChoice.cancellable
      ? [...choices, ...legal('Cancel choice', { type: 'RESOLVE_CHOICE', player, key: null })]
      : choices;
  }
  if (state.step === 'counter') {
    return [
      ...actor.supports.flatMap((support, slot) =>
        support
          ? legal(`Activate ${narutoCardName(support.cardId)}`, { type: 'ACTIVATE_SUPPORT', player, slot })
          : [],
      ),
      ...legal('Pass priority', { type: 'PASS_COUNTER', player }),
    ];
  }

  const actions: NarutoActionOption[] = [];
  for (const card of actor.hand) {
    const name = narutoCardName(card.cardId);
    actions.push(...legal(`Summon ${name}`, { type: 'SUMMON', player, handUid: card.uid }));
    actions.push(...legal(`Set ${name} as support`, { type: 'SET_SUPPORT', player, handUid: card.uid }));
    actions.push(
      ...legal(`Play ${name} support`, { type: 'ACTIVATE_SUPPORT_FROM_HAND', player, handUid: card.uid }),
    );
  }
  actions.push(...legal('Activate Leader effect', { type: 'LEADER_EFFECT', player }));
  actions.push(...legal('Recovery', { type: 'RECOVERY', player }));

  const targets = [
    { label: `${opponent.name}'s Leader`, targetKind: 'leader' as const, targetUid: `leader:${opponentId}` },
    ...opponent.characters.flatMap((character) =>
      character
        ? [
            {
              label: narutoCardName(character.cardId),
              targetKind: 'character' as const,
              targetUid: character.uid,
            },
          ]
        : [],
    ),
  ];
  for (const target of targets) {
    actions.push(
      ...legal(`Attack ${target.label}`, {
        type: 'DECLARE_ATTACK',
        player,
        attackerKind: 'leader',
        attackerUid: `leader:${player}`,
        targetKind: target.targetKind,
        targetUid: target.targetUid,
      }),
    );
  }
  for (const character of actor.characters) {
    if (!character) continue;
    const name = narutoCardName(character.cardId);
    actions.push(...legal(`Activate ${name}`, { type: 'ACTIVATE_CHARACTER', player, uid: character.uid }));
    for (const target of targets) {
      actions.push(
        ...legal(`${name}: attack ${target.label}`, {
          type: 'DECLARE_ATTACK',
          player,
          attackerKind: 'character',
          attackerUid: character.uid,
          targetKind: target.targetKind,
          targetUid: target.targetUid,
        }),
      );
    }
  }
  actions.push(...legal('End turn', { type: 'END_TURN', player }));
  return actions;
}
